title: noraworld.io
#description:
permalink: :title
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME

sass:
  style: compressed
